apiVersion: v1
kind: Secret
metadata:
  name: sample-stackrox-prometheus-additional-scrape-configs
stringData:
  prometheus-additional.yaml: |
    - job_name: 'sample-stackrox-metrics'
      scheme: https
      metrics_path: /metrics
      bearer_token_file: /var/run/secrets/tokens/token
      tls_config:
        ca_file: /etc/prometheus/rhacs-ca/service-ca.crt
      static_configs:
      - targets: ['central-ocp.${NAMESPACE}.svc:443']
