apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: sample-stackrox-monitoring-stack
  namespace: stackrox
  finalizers:
    - monitoring.observability.openshift.io/finalizer
  labels:
    app: monitoring
spec:
  alertmanagerConfig:
    disabled: false
  prometheusConfig:
    replicas: 1
  resourceSelector:
    matchLabels:
      app: central
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  retention: 1d
